# SPDX-FileCopyrightText: 2022 Intel Corporation
#
# SPDX-License-Identifier: MIT

environment:
  global:
    WINDOWS_BASEKIT_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/62641e01-1e8d-4ace-91d6-ae03f7f8a71f/w_BaseKit_p_2024.0.0.49563_offline.exe
    WINDOWS_HPCKIT_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/5b36181e-4974-4733-91c7-0c10c54900a5/w_HPCKit_p_2024.0.0.49588_offline.exe
    LINUX_BASEKIT_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/20f4e6a1-6b0b-4752-b8c1-e5eacba10e01/l_BaseKit_p_2024.0.0.49564_offline.sh
    LINUX_HPCKIT_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/1b2baedd-a757-4a79-8abb-a5bf15adae9a/l_HPCKit_p_2024.0.0.49589_offline.sh
    WINDOWS_CPP_COMPONENTS: intel.oneapi.win.cpp-dpcpp-common
    WINDOWS_FORTRAN_COMPONENTS: intel.oneapi.win.ifort-compiler
    WINDOWS_DPCPP_COMPONENTS: intel.oneapi.win.cpp-dpcpp-common
    LINUX_CPP_COMPONENTS: intel-oneapi-dpcpp-cpp-compiler
    LINUX_FORTRAN_COMPONENTS: intel-oneapi-compiler-fortran
    LINUX_DPCPP_COMPONENTS: intel-oneapi-compiler-dpcpp-cpp
    LINUX_CPP_COMPONENTS_WEB: intel.oneapi.lin.dpcpp-cpp-compiler
    LINUX_FORTRAN_COMPONENTS_WEB: intel.oneapi.lin.ifort-compiler
    LINUX_DPCPP_COMPONENTS_WEB: intel.oneapi.lin.dpcpp-cpp-compiler
    SAMPLES_TAG: 2024.0.0
    VS_VER: vs2019

  matrix:
    - job_name: build_windows_cpp
      appveyor_build_worker_image: Visual Studio 2019

    - job_name: build_windows_fortran
      appveyor_build_worker_image: Visual Studio 2019

    - job_name: build_windows_dpcpp
      appveyor_build_worker_image: Visual Studio 2019

    - job_name: build_linux_cpp
      appveyor_build_worker_image: ubuntu2004

    - job_name: build_linux_fortran
      appveyor_build_worker_image: ubuntu2004

    - job_name: build_linux_dpcpp
      appveyor_build_worker_image: ubuntu2004

    - job_name: build_linux_apt_cpp
      appveyor_build_worker_image: ubuntu2004

    - job_name: build_linux_apt_fortran
      appveyor_build_worker_image: ubuntu2004

    - job_name: build_linux_apt_dpcpp
      appveyor_build_worker_image: ubuntu2004

for:
  -
    matrix:
      only:
        - job_name: build_windows_cpp
    install:
      cmd: scripts/install_windows.bat %WINDOWS_HPCKIT_URL% %WINDOWS_CPP_COMPONENTS%
    build_script:
      cmd: scripts/build_windows.bat c++ %VS_VER% %SAMPLES_TAG%

    # Delete the following if you don't want to save install logs
    artifacts:
      - name: InstallLogs
        path: |
          extract.log
          bootstrapper*
          installer*
  -
    matrix:
      only:
        - job_name: build_windows_fortran
    install:
      cmd: scripts/install_windows.bat %WINDOWS_HPCKIT_URL% %WINDOWS_FORTRAN_COMPONENTS%
    build_script:
      cmd: scripts/build_windows.bat fortran %VS_VER% %SAMPLES_TAG%

    # Delete the following if you don't want to save install logs
    artifacts:
      - name: InstallLogs
        path: |
          extract.log
          bootstrapper*
          installer*
  -
    matrix:
      only:
        - job_name: build_windows_dpcpp
    install:
      cmd: scripts/install_windows.bat %WINDOWS_BASEKIT_URL% %WINDOWS_DPCPP_COMPONENTS%
    build_script:
      cmd: scripts/build_windows.bat dpc++ %VS_VER% %SAMPLES_TAG%

    # Delete the following if you don't want to save install logs
    artifacts:
      - name: InstallLogs
        path: |
          extract.log
          bootstrapper*
          installer*
  -
    matrix:
      only:
        - job_name: build_linux_cpp
    install:
      sh: |
        scripts/install_linux.sh $LINUX_HPCKIT_URL $LINUX_CPP_COMPONENTS_WEB
    build_script:
      sh: scripts/build_linux.sh c++ $SAMPLES_TAG

    # Delete the following if you don't want to save install logs
    artifacts:
      - name: InstallLogs
        path: |
          extract.log
          bootstrapper*
          installer*

  -
    matrix:
      only:
        - job_name: build_linux_fortran
    install:
      sh: |
        scripts/install_linux.sh $LINUX_HPCKIT_URL $LINUX_FORTRAN_COMPONENTS_WEB
    build_script:
      sh: scripts/build_linux.sh fortran $SAMPLES_TAG

    # Delete the following if you don't want to save install logs
    artifacts:
      - name: InstallLogs
        path: |
          extract.log
          bootstrapper*
          installer*

  -
    matrix:
      only:
        - job_name: build_linux_dpcpp
    install:
      sh: |
        scripts/install_linux.sh $LINUX_BASEKIT_URL $LINUX_DPCPP_COMPONENTS_WEB
    build_script:
      sh: scripts/build_linux.sh dpc++ $SAMPLES_TAG

    # Delete the following if you don't want to save install logs
    artifacts:
      - name: InstallLogs
        path: |
          extract.log
          bootstrapper*
          installer*

  -
    matrix:
      only:
        - job_name: build_linux_apt_cpp
    install:
      sh: |
        scripts/setup_apt_repo_linux.sh
        scripts/install_linux_apt.sh $LINUX_CPP_COMPONENTS
    build_script:
      sh: scripts/build_linux.sh c++ $SAMPLES_TAG
  -
    matrix:
      only:
        - job_name: build_linux_apt_fortran
    install:
      sh: |
        scripts/setup_apt_repo_linux.sh
        scripts/install_linux_apt.sh $LINUX_FORTRAN_COMPONENTS
    build_script:
      sh: scripts/build_linux.sh fortran $SAMPLES_TAG
  -
    matrix:
      only:
        - job_name: build_linux_apt_dpcpp
    install:
      sh: |
        scripts/setup_apt_repo_linux.sh
        scripts/install_linux_apt.sh $LINUX_DPCPP_COMPONENTS
    build_script:
      sh: scripts/build_linux.sh dpc++ $SAMPLES_TAG
