# SPDX-FileCopyrightText: 2020 Intel Corporation
#
# SPDX-License-Identifier: MIT

name: build_all_online_apt_dnf_scheduled

on:
  push: {}
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * *'

env:
  LINUX_COMPILER_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/2e562b6e-5d0f-4001-8121-350a828332fb/l_dpcpp-cpp-compiler_p_2024.1.0.468_offline.sh
  LINUX_FORTRAN_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/fd9342bd-7d50-442c-a3e4-f41974e14396/l_fortran-compiler_p_2024.1.0.465_offline.sh
  LINUX_ADVISOR_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/414cea14-4f3c-45f0-b854-44fb6cf9f34b/l_oneapi_advisor_p_2024.1.0.500_offline.sh
  LINUX_GDB_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/fc87666c-d626-47bc-a861-a1578d2ecbd3/l_dpcpp_dbg_p_2024.1.0.439_offline.sh
  LINUX_INSPECTOR_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/891acaab-a5b4-4a3c-9f36-60dca629e410/l_inspector_oneapi_p_2024.1.0.158_offline.sh
  LINUX_ITAC_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/644eec67-83d9-4bdd-be0d-d90587ec72ed/l_itac_oneapi_p_2022.1.0.158_offline.sh
  LINUX_VTUNE_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/671388a1-607e-463c-8d91-db4eebc2e8d2/l_oneapi_vtune_p_2024.1.0.519_offline.sh
  LINUX_DPCPPCT_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/997fe522-cedf-46da-a54d-be4f22992fa1/l_dpcpp-ct_p_2024.1.0.378_offline.sh
  LINUX_ISPC_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/ad98ac2b-d98a-4e86-804a-b6f30870ef6c/l_ispc_p_2024.1.0.726_offline.sh
  LINUX_IPP_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/c8d09493-ca9b-45b1-b720-12b8719b4136/l_ipp_oneapi_p_2021.11.0.532_offline.sh
  LINUX_IPPCP_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/a28fefdf-f67e-43a9-8e42-fcccd9da1fff/l_ippcp_oneapi_p_2021.11.0.37_offline.sh
  LINUX_MPI_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/749f02a5-acb8-4bbb-91db-501ff80d3f56/l_mpi_oneapi_p_2021.12.0.538_offline.sh
  LINUX_CCL_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/cad4b3be-a272-4ed0-b67a-3871e495cb28/l_oneapi_ccl_p_2021.12.0.311_offline.sh
  LINUX_DNNL_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/759e8b2a-cbff-4b4f-ad88-08deb7730e73/l_onednn_p_2024.1.0.571_offline.sh
  LINUX_DPL_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/d0be9e37-532e-4fde-9ac2-32c3ec5a2029/l_oneDPL_p_2022.5.0.219_offline.sh
  LINUX_MKL_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/2f3a5785-1c41-4f65-a2f9-ddf9e0db3ea0/l_onemkl_p_2024.1.0.695_offline.sh
  LINUX_TBB_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/b31f6b79-10aa-4119-a437-48fe2775633b/l_tbb_oneapi_p_2021.12.0.499_offline.sh
  LINUX_EMBREE_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/ba5dfc84-3daa-4757-af99-76c8f0f04338/l_embree_p_2024.1.0.711_offline.sh
  LINUX_OIDN_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/bc3a04c5-4758-4300-a002-5bbeac1f7e90/l_oidn_p_2024.1.0.696_offline.sh
  LINUX_OPGL_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/93bda2c5-5a43-4ea5-883e-1df4f9824084/l_openpgl_p_2024.1.0.727_offline.sh
  LINUX_OVKL_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/ecc16b93-de13-4847-b0d2-b43e8f4c2ced/l_openvkl_p_2024.1.0.730_offline.sh
  LINUX_OSPRAY_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/e92f024a-4a6b-4bac-9d6e-92aa68c51f2b/l_ospray_p_2024.1.0.736_offline.sh
  LINUX_OSPRAYSTD_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/1053f387-81d7-4edf-9cc3-10b744ee6110/l_ospray_studio_p_2024.1.0.707_offline.sh
  LINUX_COMPONENTS: intel-oneapi-dpcpp-cpp-compiler,intel-oneapi-compiler-fortran,intel-oneapi-vtune
  SAMPLES_TAG: 2024.1.0

jobs:
  build_linux_compiler_online:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: traceroute
      run: |
        sudo apt-get install -y traceroute
        sudo traceroute --tcp registrationcenter-download.intel.com
    - name: install_compiler
      run: scripts/install_linux.sh $LINUX_COMPILER_URL
      # Delete the following if you don't want to save install logs
    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          bootstrapper*
          installer*
        retention-days: 7

  build_linux_fortran_online:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: traceroute
      run: |
        sudo apt-get install -y traceroute
        sudo traceroute --tcp registrationcenter-download.intel.com
    - name: install_fortran
      run: scripts/install_linux.sh $LINUX_FORTRAN_URL
    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          bootstrapper*
          installer*
        retention-days: 7

  build_linux_advisor_online:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: traceroute
      run: |
        sudo apt-get install -y traceroute
        sudo traceroute --tcp registrationcenter-download.intel.com
    - name: install_advisor
      run: scripts/install_linux.sh $LINUX_ADVISOR_URL
    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          bootstrapper*
          installer*
        retention-days: 7

  build_linux_gdb_online:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: traceroute
      run: |
        sudo apt-get install -y traceroute
        sudo traceroute --tcp registrationcenter-download.intel.com
    - name: install_gdb
      run: scripts/install_linux.sh $LINUX_GDB_URL
    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          bootstrapper*
          installer*
        retention-days: 7

  build_linux_inspector_online:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: traceroute
      run: |
        sudo apt-get install -y traceroute
        sudo traceroute --tcp registrationcenter-download.intel.com
    - name: install_inspector
      run: scripts/install_linux.sh $LINUX_INSPECTOR_URL
    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          bootstrapper*
          installer*
        retention-days: 7

  build_linux_itac_online:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: traceroute
      run: |
        sudo apt-get install -y traceroute
        sudo traceroute --tcp registrationcenter-download.intel.com
    - name: install_itac
      run: scripts/install_linux.sh $LINUX_ITAC_URL
    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          bootstrapper*
          installer*
        retention-days: 7

  build_linux_vtune_online:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: traceroute
      run: |
        sudo apt-get install -y traceroute
        sudo traceroute --tcp registrationcenter-download.intel.com
    - name: install_vtune
      run: scripts/install_linux.sh $LINUX_VTUNE_URL
    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          bootstrapper*
          installer*
        retention-days: 7

  build_linux_dpcppct_online:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: traceroute
      run: |
        sudo apt-get install -y traceroute
        sudo traceroute --tcp registrationcenter-download.intel.com
    - name: install_dpcppct
      run: scripts/install_linux.sh $LINUX_DPCPPCT_URL
    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          bootstrapper*
          installer*
        retention-days: 7

  build_linux_ispc_online:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: traceroute
      run: |
        sudo apt-get install -y traceroute
        sudo traceroute --tcp registrationcenter-download.intel.com
    - name: install_ispc
      run: scripts/install_linux.sh $LINUX_ISPC_URL
    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          bootstrapper*
          installer*
        retention-days: 7

  build_linux_ipp_online:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: traceroute
      run: |
        sudo apt-get install -y traceroute
        sudo traceroute --tcp registrationcenter-download.intel.com
    - name: install_ipp
      run: scripts/install_linux.sh $LINUX_IPP_URL
    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          bootstrapper*
          installer*
        retention-days: 7

  build_linux_ippcp_online:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: traceroute
      run: |
        sudo apt-get install -y traceroute
        sudo traceroute --tcp registrationcenter-download.intel.com
    - name: install_ippcp
      run: scripts/install_linux.sh $LINUX_IPPCP_URL
    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          bootstrapper*
          installer*
        retention-days: 7

  build_linux_mpi_online:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: traceroute
      run: |
        sudo apt-get install -y traceroute
        sudo traceroute --tcp registrationcenter-download.intel.com
    - name: install_mpi
      run: scripts/install_linux.sh $LINUX_MPI_URL
    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          bootstrapper*
          installer*
        retention-days: 7

  build_linux_ccl_online:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: traceroute
      run: |
        sudo apt-get install -y traceroute
        sudo traceroute --tcp registrationcenter-download.intel.com
    - name: install_ccl
      run: scripts/install_linux.sh $LINUX_CCL_URL
    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          bootstrapper*
          installer*
        retention-days: 7

  build_linux_dnnl_online:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: traceroute
      run: |
        sudo apt-get install -y traceroute
        sudo traceroute --tcp registrationcenter-download.intel.com
    - name: install_dnnl
      run: scripts/install_linux.sh $LINUX_DNNL_URL
    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          bootstrapper*
          installer*
        retention-days: 7

  build_linux_dpl_online:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: traceroute
      run: |
        sudo apt-get install -y traceroute
        sudo traceroute --tcp registrationcenter-download.intel.com
    - name: install_dpl
      run: scripts/install_linux.sh $LINUX_DPL_URL
    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          bootstrapper*
          installer*
        retention-days: 7

  build_linux_mkl_online:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: traceroute
      run: |
        sudo apt-get install -y traceroute
        sudo traceroute --tcp registrationcenter-download.intel.com
    - name: install_mkl
      run: scripts/install_linux.sh $LINUX_MKL_URL
    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          bootstrapper*
          installer*
        retention-days: 7

  build_linux_tbb_online:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: traceroute
      run: |
        sudo apt-get install -y traceroute
        sudo traceroute --tcp registrationcenter-download.intel.com
    - name: install_tbb
      run: scripts/install_linux.sh $LINUX_TBB_URL
    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          bootstrapper*
          installer*
        retention-days: 7

  build_linux_embree_online:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: traceroute
      run: |
        sudo apt-get install -y traceroute
        sudo traceroute --tcp registrationcenter-download.intel.com
    - name: install_embree
      run: scripts/install_linux.sh $LINUX_EMBREE_URL
    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          bootstrapper*
          installer*
        retention-days: 7

  build_linux_oidn_online:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: traceroute
      run: |
        sudo apt-get install -y traceroute
        sudo traceroute --tcp registrationcenter-download.intel.com
    - name: install_oidn
      run: scripts/install_linux.sh $LINUX_OIDN_URL
    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          bootstrapper*
          installer*
        retention-days: 7

  build_linux_openpgl_online:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: traceroute
      run: |
        sudo apt-get install -y traceroute
        sudo traceroute --tcp registrationcenter-download.intel.com
    - name: install_openpgl
      run: scripts/install_linux.sh $LINUX_OPGL_URL
    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          bootstrapper*
          installer*
        retention-days: 7

  build_linux_openvkl_online:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: traceroute
      run: |
        sudo apt-get install -y traceroute
        sudo traceroute --tcp registrationcenter-download.intel.com
    - name: install_openvkl
      run: scripts/install_linux.sh $LINUX_OVKL_URL
    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          bootstrapper*
          installer*
        retention-days: 7

  build_linux_ospray_online:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: traceroute
      run: |
        sudo apt-get install -y traceroute
        sudo traceroute --tcp registrationcenter-download.intel.com
    - name: install_ospray
      run: scripts/install_linux.sh $LINUX_OSPRAY_URL
    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          bootstrapper*
          installer*
        retention-days: 7

  build_linux_ospraystd_online:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: traceroute
      run: |
        sudo apt-get install -y traceroute
        sudo traceroute --tcp registrationcenter-download.intel.com
    - name: install_ospraystd
      run: scripts/install_linux.sh $LINUX_OSPRAYSTD_URL
    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          bootstrapper*
          installer*
        retention-days: 7
