# SPDX-FileCopyrightText: 2020 Intel Corporation
#
# SPDX-License-Identifier: MIT

name: build_all_offline_windows_standalones

on:
  push: {}
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * *'

env:
  WINDOWS_COMPILER_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/a1d6c917-05ab-4883-b67b-4bd60abb74e5/w_dpcpp-cpp-compiler_p_2024.1.0.469_offline.exe
  WINDOWS_FORTRAN_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/f6a44238-5cb6-4787-be83-2ef48bc70cba/w_fortran-compiler_p_2024.1.0.466_offline.exe
  WINDOWS_ADVISOR_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/ea829a99-dd1b-4c63-96d8-7bac9eca57a3/w_oneapi_advisor_p_2024.1.0.498_offline.exe
  WINDOWS_GDB_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/59b83c91-a486-4647-9c2b-b8722d3d9134/w_dpcpp_dbg_p_2024.1.0.440_offline.exe
  WINDOWS_INSPECTOR_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/9cfd5f59-4dcd-4b0c-8b62-9fe7589dcd1c/w_inspector_oneapi_p_2024.1.0.157_offline.exe
  WINDOWS_ITAC_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/853bc765-526b-4633-ae07-7eaaa47a42ec/w_itac_oneapi_p_2022.1.0.157_offline.exe
  WINDOWS_VTUNE_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/7a0925fe-698d-4ad9-9f61-8a86a0f8791e/w_oneapi_vtune_p_2024.1.0.520_offline.exe
  WINDOWS_DPCPPCT_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/e92b996c-6a8d-40e1-b506-50eda52f0010/w_dpcpp-ct_p_2024.1.0.379_offline.exe
  WINDOWS_ISPC_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/8fc0285c-da26-4c8f-9766-6ff9778ddc82/w_ispc_p_2024.1.0.728_offline.exe
  WINDOWS_IPP_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/b4adec02-353b-4144-aa21-f2087040f316/w_ipp_oneapi_p_2021.11.0.533_offline.exe
  WINDOWS_IPPCP_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/8c01802f-9670-4c74-aaae-81e59c258af3/w_ippcp_oneapi_p_2021.11.0.38_offline.exe
  WINDOWS_MPI_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/fab706bb-ca1e-4cc9-b76a-a12df3cc984e/w_mpi_oneapi_p_2021.12.0.539_offline.exe
  WINDOWS_DNNL_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/fa839704-2ccf-4100-a48b-64b60f51db3d/w_onednn_p_2024.1.0.572_offline.exe
  WINDOWS_MKL_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/78da61ee-8ded-4aab-8964-fea48243b05e/w_onemkl_p_2024.1.0.696_offline.exe
  WINDOWS_DPL_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/998a4dbd-f0d2-4242-b3cb-1e4bf329dcd8/w_oneDPL_p_2022.5.0.220_offline.exe
  WINDOWS_TBB_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/c0b87e5c-1e1f-431f-b26e-dc250032e586/w_tbb_oneapi_p_2021.12.0.500_offline.exe
  WINDOWS_EMBREE_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/2ceb1087-22a4-473b-a522-694a9c3205af/w_embree_p_2024.1.0.713_offline.exe
  WINDOWS_OIDN_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/25266925-1e4e-4d3a-a95c-f88a3356d300/w_oidn_p_2024.1.0.698_offline.exe
  WINDOWS_OPGL_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/185080fa-3b66-4a3f-99e6-0e9078204a46/w_openpgl_p_2024.1.0.729_offline.exe
  WINDOWS_OVKL_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/7d3c2464-984f-4a4e-8795-aafa6f0c35c1/w_openvkl_p_2024.1.0.732_offline.exe
  WINDOWS_OSPRAY_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/73103f4b-70bf-47a7-a025-25bdf6a73150/w_ospray_p_2024.1.0.738_offline.exe
  WINDOWS_OSPRAYSTD_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/9d83093e-b984-4f97-8683-ad906bc650c5/w_ospray_studio_p_2024.1.0.709_offline.exe
  SAMPLES_TAG: 2024.1.0

jobs:
  build_compiler_windows:
    runs-on: windows-latest
    timeout-minutes: 90
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: tracert
      run: tracert -h 1 installer.repos.intel.com
    - name: install_compiler
      run: scripts/install_windows.bat $WINDOWS_COMPILER_URL

    # Delete the following if you don't want to save install logs
    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          extract.log
          bootstrapper*
          installer*
        retention-days: 7

  build_fortran_windows:
    runs-on: windows-latest
    timeout-minutes: 90
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: tracert
      run: tracert -h 1 installer.repos.intel.com
    - name: install_fortran
      run: scripts/install_windows.bat $WINDOWS_FORTRAN_URL

    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          extract.log
          bootstrapper*
          installer*
        retention-days: 7

  build_advisor_windows:
    runs-on: windows-latest
    timeout-minutes: 90
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: tracert
      run: tracert -h 1 installer.repos.intel.com
    - name: install_advisor
      run: scripts/install_windows.bat $WINDOWS_ADVISOR_URL

    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          extract.log
          bootstrapper*
          installer*
        retention-days: 7

  build_gdb_windows:
    runs-on: windows-latest
    timeout-minutes: 90
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: tracert
      run: tracert -h 1 installer.repos.intel.com
    - name: install_gdb
      run: scripts/install_windows.bat $WINDOWS_GDB_URL

    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          extract.log
          bootstrapper*
          installer*
        retention-days: 7

  build_inspector_windows:
    runs-on: windows-latest
    timeout-minutes: 90
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: tracert
      run: tracert -h 1 installer.repos.intel.com
    - name: install_inspector
      run: scripts/install_windows.bat $WINDOWS_INSPECTOR_URL

    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          extract.log
          bootstrapper*
          installer*
        retention-days: 7

  build_itac_windows:
    runs-on: windows-latest
    timeout-minutes: 90
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: tracert
      run: tracert -h 1 installer.repos.intel.com
    - name: install_itac
      run: scripts/install_windows.bat $WINDOWS_ITAC_URL

    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          extract.log
          bootstrapper*
          installer*
        retention-days: 7

  build_vtune_windows:
    runs-on: windows-latest
    timeout-minutes: 90
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: tracert
      run: tracert -h 1 installer.repos.intel.com
    - name: install_vtune
      run: scripts/install_windows.bat $WINDOWS_VTUNE_URL

    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          extract.log
          bootstrapper*
          installer*
        retention-days: 7

  build_dpcppct_windows:
    runs-on: windows-latest
    timeout-minutes: 90
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: tracert
      run: tracert -h 1 installer.repos.intel.com
    - name: install_dpcppct
      run: scripts/install_windows.bat $WINDOWS_DPCPPCT_URL

    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          extract.log
          bootstrapper*
          installer*
        retention-days: 7

  build_ispc_windows:
    runs-on: windows-latest
    timeout-minutes: 90
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: tracert
      run: tracert -h 1 installer.repos.intel.com
    - name: install_ispc
      run: scripts/install_windows.bat $WINDOWS_ISPC_URL

    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          extract.log
          bootstrapper*
          installer*
        retention-days: 7

  build_ipp_windows:
    runs-on: windows-latest
    timeout-minutes: 90
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: tracert
      run: tracert -h 1 installer.repos.intel.com
    - name: install_ipp
      run: scripts/install_windows.bat $WINDOWS_IPP_URL

    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          extract.log
          bootstrapper*
          installer*
        retention-days: 7

  build_ippcp_windows:
    runs-on: windows-latest
    timeout-minutes: 90
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: tracert
      run: tracert -h 1 installer.repos.intel.com
    - name: install_ippcp
      run: scripts/install_windows.bat $WINDOWS_IPPCP_URL

    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          extract.log
          bootstrapper*
          installer*
        retention-days: 7

  build_mpi_windows:
    runs-on: windows-latest
    timeout-minutes: 90
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: tracert
      run: tracert -h 1 installer.repos.intel.com
    - name: install_mpi
      run: scripts/install_windows.bat $WINDOWS_MPI_URL

    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          extract.log
          bootstrapper*
          installer*
        retention-days: 7

  build_dnnl_windows:
    runs-on: windows-latest
    timeout-minutes: 90
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: tracert
      run: tracert -h 1 installer.repos.intel.com
    - name: install_dnnl
      run: scripts/install_windows.bat $WINDOWS_DNNL_URL

    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          extract.log
          bootstrapper*
          installer*
        retention-days: 7

  build_mkl_windows:
    runs-on: windows-latest
    timeout-minutes: 90
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: tracert
      run: tracert -h 1 installer.repos.intel.com
    - name: install_mkl
      run: scripts/install_windows.bat $WINDOWS_MKL_URL

    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          extract.log
          bootstrapper*
          installer*
        retention-days: 7

  build_dpl_windows:
    runs-on: windows-latest
    timeout-minutes: 90
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: tracert
      run: tracert -h 1 installer.repos.intel.com
    - name: install_dpl
      run: scripts/install_windows.bat $WINDOWS_DPL_URL

    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          extract.log
          bootstrapper*
          installer*
        retention-days: 7

  build_tbb_windows:
    runs-on: windows-latest
    timeout-minutes: 90
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: tracert
      run: tracert -h 1 installer.repos.intel.com
    - name: install_tbb
      run: scripts/install_windows.bat $WINDOWS_TBB_URL

    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          extract.log
          bootstrapper*
          installer*
        retention-days: 7

  build_embree_windows:
    runs-on: windows-latest
    timeout-minutes: 90
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: tracert
      run: tracert -h 1 installer.repos.intel.com
    - name: install_embree
      run: scripts/install_windows.bat $WINDOWS_EMBREE_URL

    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          extract.log
          bootstrapper*
          installer*
        retention-days: 7

  build_oidn_windows:
    runs-on: windows-latest
    timeout-minutes: 90
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: tracert
      run: tracert -h 1 installer.repos.intel.com
    - name: install_oidn
      run: scripts/install_windows.bat $WINDOWS_OIDN_URL

    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          extract.log
          bootstrapper*
          installer*
        retention-days: 7

  build_openpgl_windows:
    runs-on: windows-latest
    timeout-minutes: 90
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: tracert
      run: tracert -h 1 installer.repos.intel.com
    - name: install_openpgl
      run: scripts/install_windows.bat $WINDOWS_OPGL_URL

    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          extract.log
          bootstrapper*
          installer*
        retention-days: 7

  build_openvkl_windows:
    runs-on: windows-latest
    timeout-minutes: 90
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: tracert
      run: tracert -h 1 installer.repos.intel.com
    - name: install_openvkl
      run: scripts/install_windows.bat $WINDOWS_OVKL_URL

    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          extract.log
          bootstrapper*
          installer*
        retention-days: 7

  build_ospray_windows:
    runs-on: windows-latest
    timeout-minutes: 90
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: tracert
      run: tracert -h 1 installer.repos.intel.com
    - name: install_ospray
      run: scripts/install_windows.bat $WINDOWS_OSPRAY_URL

    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          extract.log
          bootstrapper*
          installer*
        retention-days: 7

  build_ospraystd_windows:
    runs-on: windows-latest
    timeout-minutes: 90
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: tracert
      run: tracert -h 1 installer.repos.intel.com
    - name: install_ospraystd
      run: scripts/install_windows.bat $WINDOWS_OSPRAYSTD_URL

    - name: Saving install logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: InstallLogs_${{ github.job }}
        path: |
          extract.log
          bootstrapper*
          installer*
        retention-days: 7
